files: src/
repos:
  - repo: local
    hooks:
      - id: isort
        name: Isort
        entry: poe isort
        language: system
      - id: ruff-format
        name: Ruff Formatter
        entry: poe ruff-format
        language: system