"""blogs

Revision ID: 0514fde90519
Revises:
Create Date: 2025-02-20 20:17:27.623608

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0514fde90519"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blog",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("image_url", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_blog_slug"), "blog", ["slug"], unique=True)
    op.create_table(
        "locale",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "blog_translation",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=400), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("content", sa.String(length=5000), nullable=True),
        sa.Column("locale_id", sa.BigInteger(), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["blog.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["locale_id"], ["locale.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blog_translation")
    op.drop_table("locale")
    op.drop_index(op.f("ix_blog_slug"), table_name="blog")
    op.drop_table("blog")
    # ### end Alembic commands ###
