name: CI

on: push

jobs:
  lint:
    name: Run linters 
    runs-on: self-hosted
    services:
      postgres:
        image: postgres:11.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ${{ env.POSTGRES_DATABASE }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.13
        uses: actions/setup-python@v1
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry config settings.virtualenvs.create false
          poetry install
      - name: Lint with mypy
        run: poe mypy
      - name: Lint with pylint
        run: poe pylint
      - name: Lint with ruff
        run: poe ruff-check
      - name: Lint with flake8
        run: poe flake  
      - name: Run tests with pytest
        env:
          SECRET_KEY: secret_key
          DATABASE_URL: postgres://postgres:postgres@localhost/${{ env.POSTGRES_DATABASE }}
          ORM: sqlalchemy
        run: |
          alembic upgrade head
          poe test
